# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ConnectIqSdkManagerCli < Formula
  desc "CLI to download connectIQ resources"
  homepage "https://github.com/lindell/connect-iq-sdk-manager-cli"
  version "0.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lindell/connect-iq-sdk-manager-cli/releases/download/v0.5.0/connect-iq-sdk-manager-cli_0.5.0_Darwin_x86_64.tar.gz"
      sha256 "325c68e4c04c9a40359227c5d370ee739616d43a23411e82ac655ed4b3ff8cf5"

      def install
        bin.install "connect-iq-sdk-manager"
        bash_completion.install "completions/connect-iq-sdk-manager.bash" => "connect-iq-sdk-manager"
        zsh_completion.install "completions/connect-iq-sdk-manager.zsh" => "_connect-iq-sdk-manager"
        fish_completion.install "completions/connect-iq-sdk-manager.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lindell/connect-iq-sdk-manager-cli/releases/download/v0.5.0/connect-iq-sdk-manager-cli_0.5.0_Darwin_ARM64.tar.gz"
      sha256 "c7d265062403f3b1e6e04f186ebabce10ab1145a330883fdaf937d5be7c1904e"

      def install
        bin.install "connect-iq-sdk-manager"
        bash_completion.install "completions/connect-iq-sdk-manager.bash" => "connect-iq-sdk-manager"
        zsh_completion.install "completions/connect-iq-sdk-manager.zsh" => "_connect-iq-sdk-manager"
        fish_completion.install "completions/connect-iq-sdk-manager.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/lindell/connect-iq-sdk-manager-cli/releases/download/v0.5.0/connect-iq-sdk-manager-cli_0.5.0_Linux_ARM.tar.gz"
      sha256 "a7ff60b4bd41d2fec0d40ca391a9e8aa0751cb3b86277e999f3738ba960840cd"

      def install
        bin.install "connect-iq-sdk-manager"
        bash_completion.install "completions/connect-iq-sdk-manager.bash" => "connect-iq-sdk-manager"
        zsh_completion.install "completions/connect-iq-sdk-manager.zsh" => "_connect-iq-sdk-manager"
        fish_completion.install "completions/connect-iq-sdk-manager.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lindell/connect-iq-sdk-manager-cli/releases/download/v0.5.0/connect-iq-sdk-manager-cli_0.5.0_Linux_x86_64.tar.gz"
      sha256 "1034b3caf7e9e28d7904716e456d30bb790d75d2863704d46d069c5fa26c086d"

      def install
        bin.install "connect-iq-sdk-manager"
        bash_completion.install "completions/connect-iq-sdk-manager.bash" => "connect-iq-sdk-manager"
        zsh_completion.install "completions/connect-iq-sdk-manager.zsh" => "_connect-iq-sdk-manager"
        fish_completion.install "completions/connect-iq-sdk-manager.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lindell/connect-iq-sdk-manager-cli/releases/download/v0.5.0/connect-iq-sdk-manager-cli_0.5.0_Linux_ARM64.tar.gz"
      sha256 "4dbb8f828e0a686d88035947c3532e1beac9ff117b7d4a946ad48dce7e9e9216"

      def install
        bin.install "connect-iq-sdk-manager"
        bash_completion.install "completions/connect-iq-sdk-manager.bash" => "connect-iq-sdk-manager"
        zsh_completion.install "completions/connect-iq-sdk-manager.zsh" => "_connect-iq-sdk-manager"
        fish_completion.install "completions/connect-iq-sdk-manager.fish"
      end
    end
  end

  test do
    system "#{bin}/connect-iq-sdk-manager", "version"
  end
end
