# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ConnectIqSdkManagerCli < Formula
  desc "CLI to download connectIQ resources"
  homepage "https://github.com/lindell/connect-iq-sdk-manager-cli"
  version "0.7.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lindell/connect-iq-sdk-manager-cli/releases/download/v0.7.0/connect-iq-sdk-manager-cli_0.7.0_Darwin_ARM64.tar.gz"
      sha256 "4e7de23319953876424a34216542184997ad3827a1937da0a4a524029f88e275"

      def install
        bin.install "connect-iq-sdk-manager"
        bash_completion.install "completions/connect-iq-sdk-manager.bash" => "connect-iq-sdk-manager"
        zsh_completion.install "completions/connect-iq-sdk-manager.zsh" => "_connect-iq-sdk-manager"
        fish_completion.install "completions/connect-iq-sdk-manager.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lindell/connect-iq-sdk-manager-cli/releases/download/v0.7.0/connect-iq-sdk-manager-cli_0.7.0_Darwin_x86_64.tar.gz"
      sha256 "6ebe07b3a65e1968a995189afefe9bb81d6f8841d462dbf8b4412df067d0a388"

      def install
        bin.install "connect-iq-sdk-manager"
        bash_completion.install "completions/connect-iq-sdk-manager.bash" => "connect-iq-sdk-manager"
        zsh_completion.install "completions/connect-iq-sdk-manager.zsh" => "_connect-iq-sdk-manager"
        fish_completion.install "completions/connect-iq-sdk-manager.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/lindell/connect-iq-sdk-manager-cli/releases/download/v0.7.0/connect-iq-sdk-manager-cli_0.7.0_Linux_ARM.tar.gz"
      sha256 "f5661b9860ff9e5010bb98baed5e322db031ef6e0cef3b0ec37d46e88c23a318"

      def install
        bin.install "connect-iq-sdk-manager"
        bash_completion.install "completions/connect-iq-sdk-manager.bash" => "connect-iq-sdk-manager"
        zsh_completion.install "completions/connect-iq-sdk-manager.zsh" => "_connect-iq-sdk-manager"
        fish_completion.install "completions/connect-iq-sdk-manager.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lindell/connect-iq-sdk-manager-cli/releases/download/v0.7.0/connect-iq-sdk-manager-cli_0.7.0_Linux_ARM64.tar.gz"
      sha256 "5bd170a4040b099a98e84cd15bfc273f88fa84df67083bd4206a112f53dd463b"

      def install
        bin.install "connect-iq-sdk-manager"
        bash_completion.install "completions/connect-iq-sdk-manager.bash" => "connect-iq-sdk-manager"
        zsh_completion.install "completions/connect-iq-sdk-manager.zsh" => "_connect-iq-sdk-manager"
        fish_completion.install "completions/connect-iq-sdk-manager.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lindell/connect-iq-sdk-manager-cli/releases/download/v0.7.0/connect-iq-sdk-manager-cli_0.7.0_Linux_x86_64.tar.gz"
      sha256 "cc3b1f37cbbc78f084953670dc24f8910475b2c34b973f812ce57268d612d495"

      def install
        bin.install "connect-iq-sdk-manager"
        bash_completion.install "completions/connect-iq-sdk-manager.bash" => "connect-iq-sdk-manager"
        zsh_completion.install "completions/connect-iq-sdk-manager.zsh" => "_connect-iq-sdk-manager"
        fish_completion.install "completions/connect-iq-sdk-manager.fish"
      end
    end
  end

  test do
    system "#{bin}/connect-iq-sdk-manager", "version"
  end
end
