# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ConnectIqManager < Formula
  desc "CLI to download connectIQ resources"
  homepage "https://github.com/lindell/connect-iq-manager"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lindell/connect-iq-manager/releases/download/v0.2.0/connect-iq-manager_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "9c04066842327debd8475961af0fe06d1bad4b9fc1a5a96ce26da65d3166826d"

      def install
        bin.install "connect-iq-manager"
        bash_completion.install "completions/connect-iq-manager.bash" => "connect-iq-manager"
        zsh_completion.install "completions/connect-iq-manager.zsh" => "_connect-iq-manager"
        fish_completion.install "completions/connect-iq-manager.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lindell/connect-iq-manager/releases/download/v0.2.0/connect-iq-manager_0.2.0_Darwin_ARM64.tar.gz"
      sha256 "7512b6c9d312f139f6005892aeb5fda4806ab7970b8e316ea315f1d2fc8644f4"

      def install
        bin.install "connect-iq-manager"
        bash_completion.install "completions/connect-iq-manager.bash" => "connect-iq-manager"
        zsh_completion.install "completions/connect-iq-manager.zsh" => "_connect-iq-manager"
        fish_completion.install "completions/connect-iq-manager.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/lindell/connect-iq-manager/releases/download/v0.2.0/connect-iq-manager_0.2.0_Linux_ARM.tar.gz"
      sha256 "193144e893e37369278f4880de255550c7ea426f0ded0b83d6470eb975d0de41"

      def install
        bin.install "connect-iq-manager"
        bash_completion.install "completions/connect-iq-manager.bash" => "connect-iq-manager"
        zsh_completion.install "completions/connect-iq-manager.zsh" => "_connect-iq-manager"
        fish_completion.install "completions/connect-iq-manager.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lindell/connect-iq-manager/releases/download/v0.2.0/connect-iq-manager_0.2.0_Linux_x86_64.tar.gz"
      sha256 "1540566faf0dfb12e2f478340ab51e5b002cacbb67b75bf1903a15ef59707c16"

      def install
        bin.install "connect-iq-manager"
        bash_completion.install "completions/connect-iq-manager.bash" => "connect-iq-manager"
        zsh_completion.install "completions/connect-iq-manager.zsh" => "_connect-iq-manager"
        fish_completion.install "completions/connect-iq-manager.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lindell/connect-iq-manager/releases/download/v0.2.0/connect-iq-manager_0.2.0_Linux_ARM64.tar.gz"
      sha256 "f8620b7e3c1396d347ffade12e1b335bfb0b0a8970e7c342a811bad131fee671"

      def install
        bin.install "connect-iq-manager"
        bash_completion.install "completions/connect-iq-manager.bash" => "connect-iq-manager"
        zsh_completion.install "completions/connect-iq-manager.zsh" => "_connect-iq-manager"
        fish_completion.install "completions/connect-iq-manager.fish"
      end
    end
  end

  test do
    system "#{bin}/connect-iq-manager", "version"
  end
end
