# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ConnectIqManager < Formula
  desc "CLI to download connectIQ resources"
  homepage "https://github.com/lindell/connect-iq-manager"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lindell/connect-iq-manager/releases/download/v0.1.0/connect-iq-manager_0.1.0_Darwin_ARM64.tar.gz"
      sha256 "4259b85398b82c8e644e0fa7dd295db238d5d582ebb4ccd595069d0f7629c846"

      def install
        bin.install "connect-iq-manager"
        bash_completion.install "completions/connect-iq-manager.bash" => "connect-iq-manager"
        zsh_completion.install "completions/connect-iq-manager.zsh" => "_connect-iq-manager"
        fish_completion.install "completions/connect-iq-manager.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lindell/connect-iq-manager/releases/download/v0.1.0/connect-iq-manager_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "6c92f2ebba1a155bd9df2248c5a90fe4ac802f6107ac43d9ade1d66c0ee9f2ae"

      def install
        bin.install "connect-iq-manager"
        bash_completion.install "completions/connect-iq-manager.bash" => "connect-iq-manager"
        zsh_completion.install "completions/connect-iq-manager.zsh" => "_connect-iq-manager"
        fish_completion.install "completions/connect-iq-manager.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lindell/connect-iq-manager/releases/download/v0.1.0/connect-iq-manager_0.1.0_Linux_ARM64.tar.gz"
      sha256 "4fcbda940b1b372e3b5d95453bbf3d897420de981f4622c7eea8d0eb93d179fe"

      def install
        bin.install "connect-iq-manager"
        bash_completion.install "completions/connect-iq-manager.bash" => "connect-iq-manager"
        zsh_completion.install "completions/connect-iq-manager.zsh" => "_connect-iq-manager"
        fish_completion.install "completions/connect-iq-manager.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lindell/connect-iq-manager/releases/download/v0.1.0/connect-iq-manager_0.1.0_Linux_x86_64.tar.gz"
      sha256 "f3a04889c48cca190509ca8a6e0e011fd6563c11b297c46e408d64cff01c1674"

      def install
        bin.install "connect-iq-manager"
        bash_completion.install "completions/connect-iq-manager.bash" => "connect-iq-manager"
        zsh_completion.install "completions/connect-iq-manager.zsh" => "_connect-iq-manager"
        fish_completion.install "completions/connect-iq-manager.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/lindell/connect-iq-manager/releases/download/v0.1.0/connect-iq-manager_0.1.0_Linux_ARM.tar.gz"
      sha256 "f45df44daf8181449a392ac84886a3f848cbf759256553f66617fccda87c601d"

      def install
        bin.install "connect-iq-manager"
        bash_completion.install "completions/connect-iq-manager.bash" => "connect-iq-manager"
        zsh_completion.install "completions/connect-iq-manager.zsh" => "_connect-iq-manager"
        fish_completion.install "completions/connect-iq-manager.fish"
      end
    end
  end

  test do
    system "#{bin}/connect-iq-manager", "version"
  end
end
