# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ConnectIqManager < Formula
  desc "CLI to download connectIQ resources"
  homepage "https://github.com/lindell/connect-iq-manager"
  version "0.2.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lindell/connect-iq-manager/releases/download/v0.2.1/connect-iq-manager_0.2.1_Darwin_ARM64.tar.gz"
      sha256 "578532d30711e826df2a35ee29d8940263d79e81df22e3cc33a80eecf07bb2b4"

      def install
        bin.install "connect-iq-manager"
        bash_completion.install "completions/connect-iq-manager.bash" => "connect-iq-manager"
        zsh_completion.install "completions/connect-iq-manager.zsh" => "_connect-iq-manager"
        fish_completion.install "completions/connect-iq-manager.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lindell/connect-iq-manager/releases/download/v0.2.1/connect-iq-manager_0.2.1_Darwin_x86_64.tar.gz"
      sha256 "13e5cc6b931cb2d7ee417a3bf4fd6133a8b4c310a82ebb4c906dad6a039bab1c"

      def install
        bin.install "connect-iq-manager"
        bash_completion.install "completions/connect-iq-manager.bash" => "connect-iq-manager"
        zsh_completion.install "completions/connect-iq-manager.zsh" => "_connect-iq-manager"
        fish_completion.install "completions/connect-iq-manager.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lindell/connect-iq-manager/releases/download/v0.2.1/connect-iq-manager_0.2.1_Linux_x86_64.tar.gz"
      sha256 "489fe42b573d1843c8f980a10337bcc4267a36b2fe4a1f5ecc3fff270b3905ba"

      def install
        bin.install "connect-iq-manager"
        bash_completion.install "completions/connect-iq-manager.bash" => "connect-iq-manager"
        zsh_completion.install "completions/connect-iq-manager.zsh" => "_connect-iq-manager"
        fish_completion.install "completions/connect-iq-manager.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/lindell/connect-iq-manager/releases/download/v0.2.1/connect-iq-manager_0.2.1_Linux_ARM.tar.gz"
      sha256 "0cf128e6b981c2cdf41530ac874cf4f200bb3dab3a03ae8cbd3c32c0430f6c4e"

      def install
        bin.install "connect-iq-manager"
        bash_completion.install "completions/connect-iq-manager.bash" => "connect-iq-manager"
        zsh_completion.install "completions/connect-iq-manager.zsh" => "_connect-iq-manager"
        fish_completion.install "completions/connect-iq-manager.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lindell/connect-iq-manager/releases/download/v0.2.1/connect-iq-manager_0.2.1_Linux_ARM64.tar.gz"
      sha256 "052566b856c73865bdfbe9b55f1c6e9d73802a6464762cad3fde0e8d3b289707"

      def install
        bin.install "connect-iq-manager"
        bash_completion.install "completions/connect-iq-manager.bash" => "connect-iq-manager"
        zsh_completion.install "completions/connect-iq-manager.zsh" => "_connect-iq-manager"
        fish_completion.install "completions/connect-iq-manager.fish"
      end
    end
  end

  test do
    system "#{bin}/connect-iq-manager", "version"
  end
end
